_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: silu
augment:
    value: true
batch_size:
    value: 64
dense_neurons:
    value: 512
dropout:
    value: 0.3
epochs:
    value: 10
kernel_size:
    value: 3
lr:
    value: 0.001
num_classes:
    value: 1010
num_filters:
    value:
        - 32
        - 64
        - 128
        - 256
        - 512
use_batchnorm:
    value: true
