wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: half
filters_base:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.004887427934365009
