wandb_version: 1

activation:
  value: gelu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
kernel_size:
  value: 5
lr:
  value: 0.002738691213185159
