wandb_version: 1

activation:
  value: relu
augment:
  value: false
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 5
lr:
  value: 0.006284265811693216
