wandb_version: 1

activation:
  value: relu
augment:
  value: false
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
kernel_size:
  value: 3
lr:
  value: 0.006372647729910218
