wandb_version: 1

activation:
  value: mish
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 15
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 3
lr:
  value: 0.0009146572282451656
