wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 15
filter_organization:
  value: double
filters_base:
  value: 3
kernel_size:
  value: 3
lr:
  value: 0.00909111805021329
