wandb_version: 1

activation:
  value: silu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 32
kernel_size:
  value: 3
lr:
  value: 0.008157535777977298
