wandb_version: 1

activation:
  value: gelu
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 20
filter_organization:
  value: half
filters_base:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.0008434580312353674
