_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 2
                - 3
                - 16
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": windows-amd64
backbone:
    value: resnet50
batch_size:
    value: 64
epochs:
    value: 50
freeze_k:
    value: 10
freeze_percent:
    value: 0.6
strategy:
    value: last_only
