wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: same
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.006185044112100451
