wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: half
filters_base:
  value: 16
kernel_size:
  value: 5
lr:
  value: 0.006727206200324323
