_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: relu
augment:
    value: false
batch_norm:
    value: false
batch_size:
    value: 32
dense_neurons:
    value: 512
dropout:
    value: 0.3
epochs:
    value:
        - 5
        - 15
        - 25
filters:
    value:
        - 32
        - 32
        - 32
        - 32
        - 32
kernel_size:
    value: 5
lr:
    value: 0.006284265811693216
