wandb_version: 1

activation:
  value: silu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 5
filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
kernel_size:
  value: 3
lr:
  value: 0.005634829742083083
