wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 5
lr:
  value: 0.006034475893899681
