wandb_version: 1

activation:
  value: silu
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 5
lr:
  value: 0.00040823425409281254
