wandb_version: 1

activation:
  value: mish
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 15
filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
kernel_size:
  value: 3
lr:
  value: 0.006252226511056705
