wandb_version: 1

activation:
  value: mish
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: half
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.0010065963469305442
