wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
kernel_size:
  value: 5
lr:
  value: 0.0001483585732181514
