wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value:
  - 5
  - 15
  - 25
filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
kernel_size:
  value: 5
lr:
  value: 0.006134297239344743
