wandb_version: 1

activation:
  value: mish
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: double
filters_base:
  value: 8
kernel_size:
  value: 5
lr:
  value: 0.007719161782837825
