wandb_version: 1

activation:
  value: silu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 15
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 5
lr:
  value: 0.0010137082485823237
