wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 15
filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 3
lr:
  value: 0.0023524172275017938
