wandb_version: 1

activation:
  value: relu
augment:
  value: false
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.005972908079305005
