wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: same
filters_base:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.00818944655360071
