_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: relu
augment:
    value: false
batch_norm:
    value: false
batch_size:
    value: 32
dense_neurons:
    value: 256
dropout:
    value: 0.3
epochs:
    value: 10
filter_organization:
    value: same
filters_base:
    value: 64
kernel_size:
    value: 3
lr:
    value: 0.006529029543130769
