_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 2
                - 3
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": windows-amd64
activation:
    value: relu
augment:
    value: true
batch_norm:
    value: true
batch_size:
    value: 32
dense_neurons:
    value: 512
dropout:
    value: 0.2
epochs:
    value: 15
filter_organization:
    value: double
filters_base:
    value: 3
kernel_size:
    value: 3
lr:
    value: 0.00909111805021329
