wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: half
filters_base:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.008518440192386258
