wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 20
filter_organization:
  value: double
filters_base:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.007305138920289157
