wandb_version: 1

activation:
  value: silu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 8
kernel_size:
  value: 5
lr:
  value: 0.005501651212770391
