wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: half
filters_base:
  value: 16
kernel_size:
  value: 3
lr:
  value: 0.008660068174708817
