wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 15
filter_organization:
  value: same
filters_base:
  value: 16
kernel_size:
  value: 3
lr:
  value: 0.009664351659006316
