wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 15
filter_organization:
  value: double
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.009258236373996791
