wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 15
filter_organization:
  value: half
filters_base:
  value: 3
kernel_size:
  value: 5
lr:
  value: 0.00022234669784159435
