wandb_version: 1

activation:
  value: gelu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.00863853436452905
