wandb_version: 1

activation:
  value: silu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: double
filters_base:
  value: 32
kernel_size:
  value: 5
lr:
  value: 0.0029057302966120045
