wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: same
filters_base:
  value: 16
kernel_size:
  value: 3
lr:
  value: 0.002788808285428277
