wandb_version: 1

activation:
  value: mish
augment:
  value: true
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 15
filter_organization:
  value: double
filters_base:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.008256949888905483
