wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: double
filters_base:
  value: 64
kernel_size:
  value: 5
lr:
  value: 0.001759031773855202
