wandb_version: 1

activation:
  value: silu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
epochs:
  value: 10
filter_organization:
  value: double
filters_base:
  value: 16
kernel_size:
  value: 3
lr:
  value: 0.00736061899453726
