wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 3
kernel_size:
  value: 5
lr:
  value: 0.009419654399792388
