wandb_version: 1

activation:
  value: mish
augment:
  value: false
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.2
epochs:
  value: 10
filter_organization:
  value: same
filters_base:
  value: 64
kernel_size:
  value: 3
lr:
  value: 0.008750990659904473
