wandb_version: 1

activation:
  value: gelu
augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 5
filter_organization:
  value: same
filters_base:
  value: 16
kernel_size:
  value: 5
lr:
  value: 0.0024270082895842607
