_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 2
                - 3
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: silu
augment:
    value: false
batch_norm:
    value: false
batch_size:
    value: 64
dense_neurons:
    value: 512
dropout:
    value: 0.2
epochs:
    value: 25
filters:
    value:
        - 64
        - 64
        - 64
        - 64
        - 64
kernel_size:
    value: 3
lr:
    value: 0.0017723492080619215
